const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),message=document.querySelector("#message"),scoreEl=document.querySelector("#score"),comboEl=document.querySelector("#combo"),timeEl=document.querySelector("#time"),bestEl=document.querySelector("#best"),start=document.querySelector("#start"),toast=document.querySelector("#toast"),zoneEl=document.querySelector("#zone"),evoEl=document.querySelector("#evo"),bossHud=document.querySelector("#bossHud"),bossHp=document.querySelector("#bossHp"),statsPanel=document.querySelector("#runStats"),missionPanel=document.querySelector("#missions");
const dashBtn=document.querySelector("#dash"),shieldBtn=document.querySelector("#shield"),pulseBtn=document.querySelector("#pulse"),dashFill=document.querySelector("#dashFill"),shieldFill=document.querySelector("#shieldFill"),pulseFill=document.querySelector("#pulseFill");
const COLS=32,ROWS=20,RUN_TIME=300000;
let snake=[],dir,next,energy=null,core=null,hazards=[],hunters=[],powerups=[],boss=null,score=0,combo=1,alive=false,startedAt=0,timer,spawnClock=0,eventClock=0,hunterClock=0,bossClock=0,level=1,zone=0,shieldUntil=0,pulseUntil=0,dashReady=0,shieldReady=0,pulseReady=0,stats={energy:0,cores:0,hunters:0,wardens:0,damage:0};
const best=()=>Number(localStorage.getItem("snake-evolution-best")||0);
const missions=()=>JSON.parse(localStorage.getItem("snake-evolution-missions")||"{}");
const saveMissions=m=>localStorage.setItem("snake-evolution-missions",JSON.stringify(m));
const same=(a,b)=>a.x===b.x&&a.y===b.y,rand=()=>({x:Math.floor(Math.random()*COLS),y:Math.floor(Math.random()*ROWS)});
const zoneNames=["NEON GRID","HAZARD SECTOR","DARK SECTOR","Warden Territory","FINAL LOCKDOWN"];
const evoNames=["RUNNER","CHARGER","PHANTOM","OVERLORD"];
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(canvas.width/COLS,0,0,canvas.height/ROWS)}addEventListener("resize",resize);resize();
function free(){let p,t=0;do{p=rand();t++}while(t<600&&(snake.some(s=>same(s,p))||hazards.some(s=>same(s,p))||hunters.some(s=>same(s,p))||powerups.some(s=>same(s,p))||(energy&&same(energy,p))||(core&&same(core,p))||(boss&&same(boss,p))));return p}
function currentZone(){return Math.min(4,Math.floor((performance.now()-startedAt)/60000))}
function currentLevel(){return Math.min(4,1+Math.floor(score/600))}
function hud(){scoreEl.textContent=score;comboEl.textContent="x"+combo;bestEl.textContent=best();const left=Math.max(0,RUN_TIME-(performance.now()-startedAt));timeEl.textContent=Math.floor(left/60000)+":"+String(Math.ceil((left%60000)/1000)).padStart(2,"0");zone=currentZone();level=currentLevel();zoneEl.textContent=zoneNames[zone];evoEl.textContent=evoNames[level-1];if(boss){bossHud.classList.add("show");bossHp.textContent=boss.hp+"/"+boss.maxHp}else bossHud.classList.remove("show")}
function say(t){toast.textContent=t;toast.classList.add("show");clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove("show"),1000)}
function reset(){snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];dir=next={x:1,y:0};score=0;combo=1;hazards=[];hunters=[];powerups=[];boss=null;spawnClock=0;eventClock=0;hunterClock=0;bossClock=0;level=1;zone=0;stats={energy:0,cores:0,hunters:0,wardens:0,damage:0};energy=free();core=null;shieldUntil=pulseUntil=0;dashReady=shieldReady=pulseReady=0;alive=true;startedAt=performance.now();message.style.display="none";statsPanel.classList.remove("show");missionPanel.classList.remove("show");start.textContent="RUN AGAIN";hud();draw();move()}
function setDir(x,y){if(alive&&!(x===-dir.x&&y===-dir.y))next={x,y}}
function useDash(){if(!alive||performance.now()<dashReady)return;dashReady=performance.now()+7000;say("DASH // OVERRIDE");move(true)}
function useShield(){if(!alive||performance.now()<shieldReady)return;shieldReady=performance.now()+12000;shieldUntil=performance.now()+2500;say("SHIELD // ACTIVE")}
function usePulse(){if(!alive||performance.now()<pulseReady)return;pulseReady=performance.now()+15000;pulseUntil=performance.now()+350;hunters=hunters.filter(h=>Math.abs(h.x-snake[0].x)+Math.abs(h.y-snake[0].y)>8);hazards=hazards.filter(h=>Math.abs(h.x-snake[0].x)+Math.abs(h.y-snake[0].y)>5);if(boss){boss.hp=Math.max(0,boss.hp-2);if(boss.hp===0)destroyBoss()}score+=25;say("PULSE // CLEAR");hud()}
function key(e){const k=e.key.toLowerCase();if(k==="arrowup"||k==="w")setDir(0,-1);if(k==="arrowdown"||k==="s")setDir(0,1);if(k==="arrowleft"||k==="a")setDir(-1,0);if(k==="arrowright"||k==="d")setDir(1,0);if(k===" ")useDash();if(k==="shift")useShield();if(k==="e")usePulse()}
addEventListener("keydown",key);document.querySelectorAll("[data-dir]").forEach(b=>b.addEventListener("pointerdown",()=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];setDir(...d)}));start.onclick=reset;dashBtn.onclick=useDash;shieldBtn.onclick=useShield;pulseBtn.onclick=usePulse;
function spawnWave(){const lv=Math.min(5,1+Math.floor((performance.now()-startedAt)/60000));const count=Math.min(1+Math.floor(lv/2),5);while(hunters.length<count)hunters.push({...free(),type:Math.random()<.35?"interceptor":"hunter"});if(lv>=2&&hazards.length<4+lv)hazards.push(free());if(lv>=3&&Math.random()<.65)powerups.push({...free(),type:["overdrive","magnet","repair"][Math.floor(Math.random()*3)]});say("WAVE // LV"+lv)}
function hunterStep(){hunters.forEach(h=>{const dx=snake[0].x-h.x,dy=snake[0].y;if(h.type==="interceptor"&&Math.abs(dx)+Math.abs(dy)<10){h.x+=Math.sign(dx);h.y+=Math.sign(dy)}else if(Math.abs(dx)>Math.abs(dy))h.x+=Math.sign(dx);else h.y+=Math.sign(dy);h.x=(h.x+COLS)%COLS;h.y=(h.y+ROWS)%ROWS})}
function spawnBoss(){if(boss)return;boss={...free(),hp:12,maxHp:12};stats.wardens++;say("WARDEN // BOSS INBOUND")}
function destroyBoss(){if(!boss)return;boss=null;score+=1000;say("WARDEN DESTROYED // +1000")}
function bossStep(){if(!boss)return;bossClock++;if(bossClock%5)return;const dx=snake[0].x-boss.x,dy=snake[0].y-boss.y;if(Math.abs(dx)>Math.abs(dy))boss.x+=Math.sign(dx);else boss.y+=Math.sign(dy);boss.x=(boss.x+COLS)%COLS;boss.y=(boss.y+ROWS)%ROWS;if(bossClock%15===0)hazards.push(free())}
function collectPowerup(head){const i=powerups.findIndex(x=>same(x,head));if(i<0)return;const type=powerups[i].type;powerups.splice(i,1);if(type==="overdrive"){dashReady=performance.now();score+=100;say("OVERDRIVE // DASH READY")}else if(type==="magnet"){energy=free();core=free();score+=75;say("MAGNET // LOOT RELOCATED")}else{snake.push({...snake[snake.length-1]});score+=150;say("REPAIR // +LENGTH")}}
function missionCheck(){const m=missions(),done=[];if(stats.energy>=25&&!m.energy25){m.energy25=1;done.push("COLLECTOR")}if(stats.cores>=5&&!m.core5){m.core5=1;done.push("CORE HUNTER")}if(stats.hunters>=10&&!m.hunter10){m.hunter10=1;done.push("HUNTER")}if(combo>=9&&!m.combo9){m.combo9=1;done.push("COMBO MASTER")}if(stats.wardens>=1&&!m.warden){m.warden=1;done.push("WARDEN SLAYER")}if(stats.damage===0&&!alive&&!m.nohit){m.nohit=1;done.push("NO HIT")}saveMissions(m);if(done.length)say("MISSION // "+done.join(" + "))}
function move(force=false){if(!alive)return;dir=next;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=COLS||head.y<0||head.y>=ROWS)return end();const protectedNow=performance.now()<shieldUntil||performance.now()<pulseUntil;
if(!protectedNow&&(snake.some((s,i)=>i>0&&same(s,head))||hazards.some(h=>same(h,head))||hunters.some(h=>same(h,head))||(boss&&same(boss,head)))){stats.damage++;return end()}
snake.unshift(head);let grow=false;
if(energy&&same(head,energy)){score+=10*combo;combo=Math.min(9,combo+1);stats.energy++;energy=free();grow=true;if(stats.energy%3===0){core=free();say("CORE SPAWNED")}}
if(core&&same(head,core)){const gain=50*combo;score+=gain;combo=Math.min(9,combo+1);stats.cores++;core=null;energy=free();grow=true;say("CORE +"+gain)}
collectPowerup(head);if(boss&&same(head,boss)&&protectedNow){boss.hp--;score+=100;if(boss.hp<=0)destroyBoss()}
if(!grow)snake.pop();spawnClock++;eventClock++;hunterClock++;
if(spawnClock%32===0&&hazards.length<Math.min(3+level+zone,11))hazards.push(free());
if(eventClock%82===0&&hunters.length<Math.min(2+level,6))spawnWave();
if(eventClock%150===0&&zone>=2)spawnBoss();
if(hunterClock%3===0&&hunters.length)hunterStep();bossStep();
if(eventClock%70===0)combo=Math.max(1,combo-1);
const elapsed=performance.now()-startedAt;if(elapsed>=RUN_TIME)return win();
missionCheck();hud();updateAbilityUI();draw();timer=setTimeout(move,Math.max(48,118-combo*6-(force?35:0)))}
function statsMarkup(win){const bestScore=best(),newRecord=score>=bestScore&&score>0;return '<h2>'+(win?"SURVIVAL COMPLETE":"RUN OVER")+'</h2><div class="stats-grid"><span>SCORE<strong>'+score+'</strong></span><span>TIME<strong>'+timeEl.textContent+'</strong></span><span>COMBO<strong>x'+combo+'</strong></span><span>ENERGY<strong>'+stats.energy+'</strong></span><span>CORES<strong>'+stats.cores+'</strong></span><span>HUNTERS<strong>'+stats.hunters+'</strong></span><span>WARDENS<strong>'+stats.wardens+'</strong></span><span>ZONE<strong>'+zoneNames[zone]+'</strong></span></div>'+(newRecord?'<b class="record">NEW RECORD!</b>':'')}
function end(){alive=false;clearTimeout(timer);if(score>best())localStorage.setItem("snake-evolution-best",score);missionCheck();message.querySelector("p").textContent="The run ended. Review your stats below.";message.style.display="grid";statsPanel.innerHTML=statsMarkup(false);statsPanel.classList.add("show");missionPanel.classList.add("show");hud();updateAbilityUI()}
function win(){alive=false;clearTimeout(timer);score+=500+level*100;const bonus=500+level*100;missionCheck();if(score>best())localStorage.setItem("snake-evolution-best",score);message.querySelector("p").textContent="Five minutes survived. Bonus +"+bonus+".";message.style.display="grid";statsPanel.innerHTML=statsMarkup(true);statsPanel.classList.add("show");missionPanel.classList.add("show");say("SURVIVED // BONUS +"+bonus);hud();updateAbilityUI()}
function updateAbilityUI(){const now=performance.now();dashFill.style.width=(now>=dashReady?100:Math.max(0,100-(dashReady-now)/70))+"%";shieldFill.style.width=(now>=shieldReady?100:Math.max(0,100-(shieldReady-now)/120))+"%";pulseFill.style.width=(now>=pulseReady?100:Math.max(0,100-(pulseReady-now)/150))+"%"}
function pixel(p,c){ctx.fillStyle=c;ctx.fillRect(p.x+.12,p.y+.12,.76,.76);ctx.fillStyle="#0005";ctx.fillRect(p.x+.12,p.y+.72,.76,.14)}
function draw(){const z=currentZone();const bg=["#060806","#090704","#050609","#09050b","#0b0508"][z],grid=["#111a15","#21150e","#121521","#201125","#281015"][z];ctx.fillStyle=bg;ctx.fillRect(0,0,COLS,ROWS);ctx.strokeStyle=grid;ctx.lineWidth=.1;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,ROWS);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(COLS,y);ctx.stroke()}
hazards.forEach(p=>pixel(p,z>=3?"#ff3f6b":"#ff5b62"));hunters.forEach(p=>{pixel(p,p.type==="interceptor"?"#d66cff":"#66c7ff");ctx.fillStyle="#0b2634";ctx.fillRect(p.x+.3,p.y+.3,.4,.4)});powerups.forEach(p=>pixel(p,p.type==="overdrive"?"#ff9f43":p.type==="magnet"?"#a66cff":"#4de1d1"));if(boss){pixel(boss,"#ff3f8f");ctx.fillStyle="#fff";ctx.fillRect(boss.x+.18,boss.y+.18,.64,.12);ctx.fillStyle="#111";ctx.fillRect(boss.x+.18,boss.y+.18,.64*(boss.hp/boss.maxHp),.12)}if(energy)pixel(energy,"#79e35b");if(core){pixel(core,"#ffd85c");pixel({x:core.x,y:Math.max(0,core.y-1)},"#ffd85c")}snake.forEach((p,i)=>pixel(p,i?"#55bb4a":"#b8ff8d"));if(level>1){ctx.strokeStyle=level===4?"#ff3f8f":level===3?"#a66cff":"#ffd85c";ctx.lineWidth=.14;ctx.strokeRect(snake[0].x+.04,snake[0].y+.04,.92,.92)}if(performance.now()<shieldUntil){ctx.strokeStyle="#66c7ff";ctx.lineWidth=.25;ctx.strokeRect(snake[0].x+.08,snake[0].y+.08,.84,.84)}}
draw();updateAbilityUI();