const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),message=document.querySelector("#message"),scoreEl=document.querySelector("#score"),comboEl=document.querySelector("#combo"),bestEl=document.querySelector("#best"),start=document.querySelector("#start");
const COLS=32,ROWS=20;let snake,dir,next,energy,core,hazards,score,combo,alive=false,timer,last=0,spawnClock=0;
const best=()=>Number(localStorage.getItem("snake-evolution-best")||0);bestEl.textContent=best();
function resize(){const r=canvas.getBoundingClientRect();const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(canvas.width/COLS,0,0,canvas.height/ROWS,0,0)}addEventListener("resize",resize);resize();
const same=(a,b)=>a.x===b.x&&a.y===b.y, rand=()=>({x:Math.floor(Math.random()*COLS),y:Math.floor(Math.random()*ROWS)});
function free(){let p;do{p=rand()}while(snake.some(s=>same(s,p))||hazards.some(s=>same(s,p))||(energy&&same(energy,p))||(core&&same(core,p)));return p}
function reset(){snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];dir=next={x:1,y:0};score=0;combo=1;energy=free();core=null;hazards=[];alive=true;message.style.display="none";updateHUD()}
function updateHUD(){scoreEl.textContent=score;comboEl.textContent="x"+combo;bestEl.textContent=best()}
function setDir(x,y){if(!alive)return;if(x===-dir.x&&y===-dir.y)return;next={x,y}}
addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(k==="arrowup"||k==="w")setDir(0,-1);if(k==="arrowdown"||k==="s")setDir(0,1);if(k==="arrowleft"||k==="a")setDir(-1,0);if(k==="arrowright"||k==="d")setDir(1,0);if(k===" "&& !alive)reset()});
document.querySelectorAll("[data-dir]").forEach(b=>b.addEventListener("pointerdown",()=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];setDir(...d)}));start.onclick=reset;
function draw(){ctx.fillStyle="#070a09";ctx.fillRect(0,0,COLS,ROWS);ctx.strokeStyle="#111a15";ctx.lineWidth=.12;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,ROWS);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(COLS,y);ctx.stroke()}
function pixel(p,c){ctx.fillStyle=c;ctx.fillRect(p.x+.15,p.y+.15,.7,.7);ctx.fillStyle="#0005";ctx.fillRect(p.x+.15,p.y+.72,.7,.13)}
hazards.forEach(p=>{pixel(p,"#ff5b62");ctx.fillStyle="#ff9a68";ctx.fillRect(p.x+.35,p.y+.1,.3,.3)});if(energy)pixel(energy,"#79e35b");if(core){pixel(core,"#ffd85c");ctx.fillStyle="#fff3a0";ctx.fillRect(core.x+.35,core.y+.35,.3,.3)}
snake.forEach((p,i)=>{pixel(p,i===0?"#b8ff8d":"#55bb4a");if(i===0){ctx.fillStyle="#081008";ctx.fillRect(p.x+.3+(dir.x>0?.25:0),p.y+.27,.12,.12);ctx.fillRect(p.x+.58-(dir.x<0?.25:0),p.y+.27,.12,.12)}})}
function end(){alive=false;clearTimeout(timer);if(score>best())localStorage.setItem("snake-evolution-best",score);bestEl.textContent=best();message.querySelector("h2").textContent="RUN OVER";message.querySelector("p").textContent="SCORE "+score+"  •  COMBO x"+combo;start.textContent="RUN AGAIN";message.style.display="grid"}
function tick(){if(!alive)return;dir=next;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=COLS||head.y<0||head.y>=ROWS||snake.some((s,i)=>i>0&&same(s,head))||hazards.some(s=>same(s,head))){end();return}snake.unshift(head);let grew=false;if(energy&&same(head,energy)){score+=10*combo;combo=Math.min(combo+1,9);energy=free();grew=true;if(combo%3===0)core=free()}if(core&&same(head,core)){score+=50*combo;combo=Math.min(combo+1,9);core=null;energy=free();grew=true}if(!grew){snake.pop()}spawnClock++;if(spawnClock%35===0&&hazards.length<7)hazards.push(free());if(spawnClock%70===0&&combo>1)combo=Math.max(1,combo-1);updateHUD();draw();timer=setTimeout(tick,Math.max(55,125-combo*6))}
function loop(t){if(alive&&t-last>1000/60){last=t;draw()}requestAnimationFrame(loop)}requestAnimationFrame(loop);draw();